### PR TITLE
Use RegExp to detect info hash

### PR DESCRIPTION
**Pull request by jaruba**

### CODE REVIEW

**Comment by feross** [comment]
Thanks for the PR. One issue: the base32 handling is wrong. [The RFC](https://www.ietf.org/rfc/rfc3548.txt) says that the characters A-Z and 2-7 make up base32.

Can you update the PR?

**Comment by feross** [comment]
Also, you can remove the parens in the regex, too. I don't think those are necessary.

**Comment by jaruba** [comment]
sure, `len` could also be removed, as it is only needed for 1 check (if you don't think it will be necessary for others in the future)

**Comment by feross** [comment]
Yeah, that sounds good. And since we know it's a Buffer in that check, you can save the existence check.

**Comment by jaruba** [comment]
b36a368315d2bea6dce818e21ac46c97a7ccd8fc

**Comment by feross** [comment]
Released as 5.4.0.

**Pull request merged**
